version: '3'
services:
  mongo-atlas:
    image: mongodb/mongodb-atlas-local:latest
    container_name: mongodb-atlas
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_INITDB_DATABASE: semantic-search
      DO_NOT_TRACK: 1
